var GAME_LEVELS = [

  ["                                                                                                                              ",
   "   @                                                                                                                          ",
   "   -                                                                                                                          ",
   "                                                                                                                              ",
   "                                                                                                                              ",
   "                                                                                                                              ",
   "          xxx   xxxxx xxxxx   xxxxx  xxx    xxxxx x   x xxxxx   x   x x   x xxxxx xxxxx xxxxx   xxxx   xxx   xxx  xxxx        ",
   "         x      x       x       x   x   x     x   x   x x       x x x x   x   x     x   x       x   x x   x x   x x   x       ",
   "         x      xxxx    x       x   x   x     x   xxxxx xxxx    x x x xxxxx   x     x   xxxx    x   x x   x x   x xxxx        ",
   "         x  xx  x       x       x   x   x     x   x   x x       x x x x   x   x     x   x       x   x x   x x   x x x         ",
   "          xxx   xxxxx   x       x    xxx      x   x   x xxxxx    x x  x   x xxxxx   x   xxxxx   xxxx   xxx   xxx  x  x        ",
   "                                                                                                                              ",
   "                                                                                                                         o    ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                        yyyyyyyyyyyyyyyyy       ",
   "       yyyyyyyyyyyyyyyyyyyyyyyyy                   yyyyyyyyyyyyyyy    yyyyyyyyy ",
   "        yyyyyyyyyyyyyyyyyyyyyyy                       yyyyyyyyyyyyyyyyyyyyy     ",
   "      yyyyyyyyyyyyyyyy                                     yyyyyyyyy            ",
   "                                                                                ",
   "                                   x                                            ",
   "                                  x!x                                           ",
   "                                 x!!!x                                          ",
   "                                 x!!!x                                          ",
   "                                xx!!!xx                                         ",
   "  @                            x!!!!!!!x                                     o   ",
   "  x                     xx     x!!!!!!!x                                     x  ",
   "  xx                           x!!!!!!!x                                    xx  ",
   "  xxx                         x!!x!!!x!!x                                  xxx  ",
   "  xxxx            xx         x!!!!!!!!!!!x                                xxxx  ",
   "  xxxxx                ^   ^x!!!!!!!!!!!!!x^   ^                         xxxxx  ",
   "  xxxxxx             x!!!!!!!!!!!!!!!!!!!!!!!!!!!x    x    x            xxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxx!xxx!xxxxxx!!!xxxxxx!xxx!xxxxxxx!!!!xxxxxxxxxxxxxxxxxxx  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                   ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                   ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                     ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                     ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                     ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxx                     "],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x!!!!!x                                                                                                           ",
   "xVVVV x                                                                                                           ",
   "x     x                                                                                                           ",
   "x     x       yyyyyyyyyyyyyyy                                                                                     ",
   "x     x    yyyyyyyyyyyyyyy                                                                                        ",
   "x     x      yyyyyyyyyyyyyyy                                                                                      ",
   "x     x        yyyyyy                                                                                             ",
   "x  @  x                                                                                                           ",
   "x     x                                                                                                           ",
   "x     x                                                                                             xxxxx    xxxxx",
   "x     x                                         xx                                                  x             ",
   "x     x                                                                                             x            <",
   "x     x                          xx                                                        xx       x             ",
   "x     x                                                                                             x >           ",
   "x                                                            xx                                     x             ",
   "x                                                                                                   x         <   ",
   "x    xx                                                          yy                                 x  >          ",
   "x     x            /                                                                                x             ",
   "x!!!!!x           xxx                                               xx             xx               x      o      ",
   "xxxxxxx   xx                 ^^^^  ^^^^^^^^^^^^^  ^^^^^^^^^^^                                       x     xxx     ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "x                            !>                  G                    x      G                               x",
   "x                            x                                        x                                      x",
   "x              !>                                x                    x              x           x        xxxx",
   "x>                           x                   x                    x              x           x           x",
   "x              x                                                                     x           xxxx    G   x",
   "x   G          x             g                   !>          g                       x     g     x       x   x",
   "x   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           x",
   "x     x                                                                                          x           x",
   "x     x                                                                                          x       xx  x",
   "x     x             yyyyyyyyyyyyyy                                                               x           x",
   "x     x         yyyyyyyyyyy                                                                      x>          x",
   "x     x                                                                      -       G           x           x",
   "x  x  x                                                                     xxx                  x           x",
   "x     x                                                xxx                                       x  xxx      x",
   "x     xx            ^^^^^^                                                                       x           x",
   "x    <!x           x!!!!!!x            x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                      x           x",
   "x     xx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxxxxxxxx          <x",
   "x     x                 x                                                           x x          x           x",
   "x     xxxxxxxxxxxxx  o  x                                                           x x          x           x",
   "x     x           xxxxxx                                                            x x          x         xxx",
   "x  x  x                                                                             x x          x           x",
   "x     x                                                                             x x          x           x",
   "x     x                                                                             x x          x           x",
   "!>    x                                                                             x x          x           x",
   "x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   x x          x           x",
   "x     x                                                         x                   x x          x           x",
   "x     x                                                         x                   x x          x           x",
   "x     x                                                         x                   x x          x           x",
   "x  x  x                                                      s  x                   x x          x           x",
   "x     xx     xxxxxxx  xxxxxxxxxxxxxx  xxxxxxxx  xxxxxxxxxxxxxx xx                   x x          x           x",
   "x    <!x    x                                                x xx                   x x          x           x",
   "x     xx                                                     x x                    x x          x           x",
   "x     xxx                                                    x x                    x x          x           x",
   "x     x                                                      x x                    x x          x        g  x",
   "x     x                                                      x x                    x x          x        xxxx",
   "x  x  x             ^^              ^^        ^^             x x                    x x          x           x",
   "x     xxxxxxxxxxxxxx!!xxxxxxxxxxxxxx!!xxxxxxxx!!xxxxx  xxxxxxx x                    x x          xxxx        x",
   "x     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxx xxxx                 x x xxxxxxxxxx           x",
   "x                                                                  xxxxxxxxxxxxxxxxxx xxx                    x",
   "x                                                                                    g  x                    x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xxxxxxxxxxxxx",
   ">                                                                                                            x",
   ">                                                                                                            x",
   ">                                                                                            xx              x",
   ">        @                        <                     <                           <                       <x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                       @                                                      ",
   "                                        xx    xx     xxxxx     xx    xx                                       ",
   "                                        xx    xx    xx   xx    xx    xx                                       ",
   "                                         xx  xx    xx     xx   xx    xx                                       ",
   "                                          xxxx    xx       xx  xx    xx                                       ",
   "                                           xx      xx     xx   xx    xx                                       ",
   "                                           xx       xx   xx     xx  xx                                        ",
   "                                           xx        xxxxx       xxxx                                         ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                        xx      xx  xxxxxx xxxx      xx                                       ",
   "                                        xx  xx  xx    xx   xx xx     xx                                       ",
   "                                        xx  xx  xx    xx   xx  xx    xx                                       ",
   "                                        xx  xx  xx    xx   xx   xx   xx                                       ",
   "                                        xx  xx  xx    xx   xx    xx  xx                                       ",
   "                                         xx xx xx     xx   xx     xx xx                                       ",
   "                                          xxxxxx    xxxxxx xx      xxxx                                       ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
